//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_BP
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Длительность.
    /// </summary>
    // *** Start programmer edit section *** (Длительность CustomAttributes)

    // *** End programmer edit section *** (Длительность CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДлительностьE", new string[] {
            "Длительность as \'Длительность\'"})]
    [View("ДлительностьL", new string[] {
            "Длительность as \'Длительность\'"})]
    public class Длительность : ICSSoft.STORMNET.DataObject
    {
        
        private int fДлительность;
        
        // *** Start programmer edit section *** (Длительность CustomMembers)

        // *** End programmer edit section *** (Длительность CustomMembers)

        
        /// <summary>
        /// Длительность.
        /// </summary>
        // *** Start programmer edit section *** (Длительность.Длительность CustomAttributes)

        // *** End programmer edit section *** (Длительность.Длительность CustomAttributes)
        public virtual int Длительность
        {
            get
            {
                // *** Start programmer edit section *** (Длительность.Длительность Get start)

                // *** End programmer edit section *** (Длительность.Длительность Get start)
                int result = this.fДлительность;
                // *** Start programmer edit section *** (Длительность.Длительность Get end)

                // *** End programmer edit section *** (Длительность.Длительность Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Длительность.Длительность Set start)

                // *** End programmer edit section *** (Длительность.Длительность Set start)
                this.fДлительность = value;
                // *** Start programmer edit section *** (Длительность.Длительность Set end)

                // *** End programmer edit section *** (Длительность.Длительность Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДлительностьE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДлительностьE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДлительностьE", typeof(IIS.Modul_ucheta_BP.Длительность));
                }
            }
            
            /// <summary>
            /// "ДлительностьL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДлительностьL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДлительностьL", typeof(IIS.Modul_ucheta_BP.Длительность));
                }
            }
        }
    }
}
